version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "0sc"
    commit-message:
      prefix: "Github Action Update"
